### PR TITLE
Updated to a standard format and checked all links.

### PR DESCRIPTION
**Pull request by JimmyBoh**
The format update was pretty basic. Ensure periods were used at the end
of lines, align all occurrances of
angular/angular.js/angularjs/Angular/AngularJS to the same thing
(AngularJS, the same way they spell it), and fix the bullet points for
the TodoMVC section.

I also navigated to each link and made sure it existed and was not
marked as _deprecated_ or _unmaintained_. Those that were deprecated,
missing, or extremely old have been removed. Unmaintained projects have
been marked with `(_unmaintained_)` after the description.

### CODE REVIEW

**Comment by JimmyBoh** [comment]
This fixed #54.

**Comment by JimmyBoh** [comment]
Have you had a chance to look at this @gianarb?

**Comment by gianarb** [comment]
Sorry for my delay can you rebase? I am ready to merge

**Comment by JimmyBoh** [comment]
Yeah, no problem.

**Comment by JimmyBoh** [comment]
Good to go, @gianarb!

**Comment by JimmyBoh** [comment]
@gianarb Actually, hold that thought. Somehow I lost my big changes. One moment.

**Comment by JimmyBoh** [comment]
Alright @gianarb, I screwed it up at first but I think it's good now. Merge away!

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
